# .github/workflows/build.yml

name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            ext: ""
          - os: windows-latest
            name: windows
            ext: ".exe"
          - os: macos-latest
            name: macos
            ext: ".app"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Build executable (Linux/Windows)
      if: matrix.os != 'macos-latest'
      run: pyinstaller --onefile --windowed --name "CleverCoffee-OTA-Flasher" clevercoffee_ota_flasher.py

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: pyinstaller --onefile --windowed --name "CleverCoffee-OTA-Flasher" clevercoffee_ota_flasher.py

    - name: Rename files for release
      shell: bash
      run: |
        cd dist
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          # For macOS, zip the .app bundle
          zip -r "CleverCoffee-OTA-Flasher-${{ matrix.name }}.zip" "CleverCoffee-OTA-Flasher.app"
          rm -rf "CleverCoffee-OTA-Flasher.app"
        else
          # For Linux/Windows, rename the executable
          mv "CleverCoffee-OTA-Flasher${{ matrix.ext }}" "CleverCoffee-OTA-Flasher-${{ matrix.name }}${{ matrix.ext }}"
        fi

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/CleverCoffee-OTA-Flasher-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
